



name: Upload Python Package to Test PyPI

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit
    - name: Build and publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        FLIT_INDEX_URL: https://test.pypi.org/legacy/
      run: |
        flit publish --format wheel 